version: "3.8"
services:
  url-shortener:
    build:
      context: ./
      dockerfile: dev.Dockerfile
    ports:
      - "8080:8080"
    # Mounting local Maven configuration and repositories for faster build.
    # Please note this is only allowed for development setup.
    volumes:
      - ~/.m2/:/root/.m2/
      - ./:/backend/
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/urlshortener
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G
        reservations:
          memory: 1G
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=urlshortener
    volumes:
      - "./docker/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
