version: '3'
services:
  urlshortener:
    build: .
    ports:
      - 8080:8080
    volumes:
      - ~/.m2/repository:/root/.m2/repository
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/urlshortener
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      - postgres
  postgres:
    image: postgres:9.6-alpine
    volumes:
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: urlshortener